spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    platform: h2
    hikari:
      connection-test-query: SELECT 1
    jpa:
      database: H2
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: validate
    flyway:
      migration: db/migration

    security:
      filter:
        order: 10
      basic:
        enabled: true
        authorize-mode: NONE
auth:
  jwt:
    issuer: "BookStore"
    audience: "Book store App"
    ttl-in-seconds: 3600
    secret: "ej7+D6Hh2r2KBEIuoGz1RGjtXooObzebSSxNm7yu2YSkEKv8aQmC2iYuxXLkKYKgT1210e5ZKMoY4XM0uQnkJkKGA01tBWZK+Pi3zX+nZvVNTJbZwRSOyZ2bm99exCq+z6ER5q5XWes1G9/sG5rp7kK9bL/NdNdU13HAFjJew6NwyxIxFH5VhXWwtgIJy+1KcJ9+3kq6uYNylrPC2U1h0xvR9qQzi1D2m9H8ZA=="

